### ISSUE TITLE
No longer working in Portugal

### ISSUE THREAD

**Issue by moodyblue** [dgomes/pyprosegur#8]
Boas, desde há algum tempo, talvez desde há 1 mês, que o script deixou de conseguir fazer login à prosegur. Já uso isto há anos e é a primeira vez que tenho problemas.

**Comment by dgomes** [comment]
Não mudaste de password no mes passado ;) ?

Partilha as mensagens de erro

**Comment by moodyblue** [comment]
Estava a usar o mesmo userid/pw no script e no telemóvel. E de repente a telemóvel começou a dizer que a pw era inválida. Depois de alguns testes detectei que o script fazia tantas tentativas falhadas de login que a prosegur invalidava a pw. Assim criei um userid adicional só para o script. Com esse userid consigo fazer login no UI da prosegur. Porém no script dá estes erros
```
Traceback (most recent call last):
  File "/share/homes/admin/pyprosegur-master/cli.py", line 112, in <module>
    prosegur(obj={})
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1150, in __call__
    return anyio.run(self._main, main, args, kwargs, **({"backend":_anyio_backend} if _anyio_backend is not None else {}))
  File "/opt/python3/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/python3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/python3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/python3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/python3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1153, in _main
    return await main(*args, **kwargs)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1074, in main
    rv = await self.invoke(ctx)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1684, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1420, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 774, in invoke
    rv = await rv
  File "/share/homes/admin/pyprosegur-master/cli.py", line 41, in installation
    installation = await Installation.retrieve(auth)
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-master/pyprosegur/installation.py", line 43, in retrieve
    resp = await auth.request("GET", "/installation")
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-master/pyprosegur/auth.py", line 66, in request
    await self.login()
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-master/pyprosegur/auth.py", line 47, in login
    raise ConnectionRefusedError("Could not login")
ConnectionRefusedError: Could not login
```

Estou a usar python 3.10.4, mas é possível que ao actualizar o sistema operativo esta versão de python seja diferente da anterior.

**Comment by dgomes** [comment]
por favor actualiza o pyprosegur:

`pip install --upgrade pyprosegur`

**Comment by moodyblue** [comment]
Em vez de upgrade instalei a versão . Continua a não fazer login, mas as mensagens de erro são diferentes
```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
INFO:pyprosegur.auth:Backing off request(...) for 0.8s (ConnectionRefusedError: Could not login)
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
INFO:pyprosegur.auth:Backing off request(...) for 4.2s (ConnectionRefusedError: Could not login)
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
ERROR:pyprosegur.auth:Giving up request(...) after 3 tries (ConnectionRefusedError: Could not login)
ERROR:pyprosegur.auth:Giving up request(...) after 1 tries (ConnectionRefusedError: Could not login)
Traceback (most recent call last):
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-0.0.10/cli.py", line 196, in <module>
    prosegur(obj={})
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1205, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/opt/python3/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 73, in run
    return async_backend.run(func, args, {}, backend_options)
  File "/opt/python3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2001, in run
    return runner.run(wrapper())
  File "/opt/python3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 193, in run
    return self._loop.run_until_complete(task)
  File "/opt/python3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/python3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1989, in wrapper
    return await func(*args)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1208, in _main
    return await main(*args, **kwargs)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1120, in main
    rv = await self.invoke(ctx)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 1485, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/opt/python3/lib/python3.10/site-packages/asyncclick/core.py", line 824, in invoke
    rv = await rv
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-0.0.10/cli.py", line 56, in installation
    installation = await Installation.retrieve(auth, contract)
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-0.0.10/pyprosegur/installation.py", line 96, in retrieve
    resp = await auth.request("GET", "/installation")
  File "/opt/python3/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/opt/python3/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-0.0.10/pyprosegur/auth.py", line 108, in request
    await self.login()
  File "/share/CACHEDEV3_DATA/homes/admin/pyprosegur-0.0.10/pyprosegur/auth.py", line 83, in login
    raise ConnectionRefusedError("Could not login")
ConnectionRefusedError: Could not login
```

**Comment by moodyblue** [comment]
No teu caso consegues fazer login à Prosegur via este script ?

**Comment by dgomes** [comment]
Consigo replicar o teu erro se tiver a password errada...

**Comment by moodyblue** [comment]
E qual é a versão de python que usas ?

**Comment by dgomes** [comment]
3.11

**Comment by moodyblue** [comment]
Terá alguma coisa a ver com verificação de certificados ?

**Comment by dgomes** [comment]
Não creio... acrescentei logging de debug - actualiza e tenta de novo.

**Comment by moodyblue** [comment]
Aqui está o novo log
```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
ERROR:pyprosegur.auth:401 LOGIN FAILED: Unauthorized
INFO:pyprosegur.auth:Backing off request(...) for 0.4s (ConnectionRefusedError: Could not login: 401 Unauthorized)
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
ERROR:pyprosegur.auth:401 LOGIN FAILED: Unauthorized
INFO:pyprosegur.auth:Backing off request(...) for 2.3s (ConnectionRefusedError: Could not login: 401 Unauthorized)
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
ERROR:pyprosegur.auth:401 LOGIN FAILED: Unauthorized
ERROR:pyprosegur.auth:Giving up request(...) after 3 tries (ConnectionRefusedError: Could not login: 401 Unauthorized)
ERROR:pyprosegur.auth:Giving up request(...) after 1 tries (ConnectionRefusedError: Could not login: 401 Unauthorized)
Could not login: 401 Unauthorized
```

**Comment by dgomes** [comment]
Não me resta qualquer dúvida... o login que usas está errado. É a API da Prosegur que o te diz

**Comment by moodyblue** [comment]
Obrigado mas deve haver alguma outra razão. O userid/pw que estou a usar funcionam na Web sem problema. Houve muitas alterações no meu sistema, vou tentar repor numa situação em que já tenha funcionado. O então foi a prosegur que bloqueou o meu IP por excesso de tentativas de login falhadas.

**Comment by moodyblue** [comment]
Fiz alguns testes, aqui estão algumas conclusões:

1) A minha password inclui um $ e passou a funcionar assim que coloquei um \ antes do $
2) No entanto o meu contrato não é encontrado, aqui tens as mensagens de erro

```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
DEBUG:pyprosegur.auth:Requesting https://smart.prosegur.com/smart-server/ws/installation {} {'Accept': 'application/json, text/plain, */*', 'Content-Type': 'application/json;charset=UTF-8', 'Origin': 'https://smart.prosegur.com/smart-individuo', 'Referer': 'https://smart.prosegur.com/smart-individuo/login.html', 'X-Smart-Token': 'eyJraWQiOiJhMTZ4UnJyT1JlUGl5SllIT01BMCtTMFBMSGJRcTV1RUxvMWJPblhBM1NFPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJmOGYzYmQ3Ny1hMTMxLTQwMDgtYTk3NC1mNjZmMmY0ODIzODkiLCJjdXN0b206aWRVc2VyIjoiMTM4MTE3NCIsImN1c3RvbTpjbGllbnRJZCI6IjExMTQxODc2OCIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbVwvZXUtY2VudHJhbC0xXzh0QXJCY2tnTiIsImN1c3RvbTppbml0aWFsaXplZCI6InRydWUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJodWdvLmNhc3RlbG9icmFuY281M0B5YWhvby5jb20iLCJjdXN0b206bGFuZ3VhZ2UiOiJlbl9HQiIsImF1dGhfdGltZSI6MTcxMzQ2NDUzNywibmlja25hbWUiOiJERVYtU01BUlQtVVNFUiIsImV4cCI6MTcxMzQ2ODEzNywiY3VzdG9tOnJvbGUiOiJEZXBlbmRlbnQiLCJpYXQiOjE3MTM0NjQ1MzcsImp0aSI6ImYyZmFkN2QxLTBhOTctNDk4YS1hYjdkLWU1NWZmZDk1YmI1YSIsImVtYWlsIjoiaHVnby5jYXN0ZWxvYnJhbmNvNTNAeWFob28uY29tIiwiY3VzdG9tOmNvdW50cnkiOiJQVCIsImN1c3RvbTpwbGF0Zm9ybSI6InNtYXJ0MiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjpmYWxzZSwiY29nbml0bzp1c2VybmFtZSI6Imh1Z28uY2FzdGVsb2JyYW5jbzUzQHlhaG9vLmNvbSIsIm9yaWdpbl9qdGkiOiI1OTViNjNkYS0yNmI1LTQwMDktYjkyNy1jYmVlODdhMDk1MDYiLCJhdWQiOiJ2M3FpajUxN2NrZnN2aXJwOHVzNHQ4ODVvIiwiZXZlbnRfaWQiOiI3NGMwN2I5MS0yNTRkLTRiNGItYjIzYi1hMTEzZmFjYmRjMGUiLCJ0b2tlbl91c2UiOiJpZCIsIm5hbWUiOiJPcGVuSEFCIiwiY3VzdG9tOm9yaWdpbiI6IldlYiIsImZhbWlseV9uYW1lIjoiQXZlaXJvIn0.kYqHqnAwiJ22--4-JMYNqNMInQlp1kCb9XwwHj6yZ1Fly_eRPMRpWMZfl564jTkDRV_TfWyvrouC6ET6KdbnRUgdQ-mA6H1aYbX5E6k-qcSaVRvnu06VHB4XRtf7OHdF1J7g_nWtmlSbusbm8sfVPPEAtnaNBBoe8brpyblc3EKcAa8ZMQSuuNdBT4t6KDoAyiL9mf_zy36exgj7umzBjLQph8nxzIp120Kg97HOKJa2gwOQI6iILfMD3kg03s6e_ygfYDE3BA15tW1NjbXnh8eelrFrqZXnb-nsHMH_9PmTH6nxzHoWQC7LbS4lAAqjzQr8d4q8uFgO1CWXFwaVQA'}
Contract 1196981 not found
```

**Comment by dgomes** [comment]
qual o resultado do:

`$ python3 cli.py USERNAME PASSWORD PT list-install` ?

PS: cuidado para não partilhares tokens de autenticação aqui (é publico!)

**Comment by moodyblue** [comment]
```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:pyprosegur.auth:No X-Smart-Token, attempting login
DEBUG:pyprosegur.auth:Requesting https://smart.prosegur.com/smart-server/ws/installation {} {'Accept': 'application/json, text/plain, */*', 'Content-Type': 'application/json;charset=UTF-8', 'Origin': 'https://smart.prosegur.com/smart-individuo', 'Referer': 'https://smart.prosegur.com/smart-individuo/login.html', 'X-Smart-Token': '******************'}
[]

```

**Comment by dgomes** [comment]
bem... não retorna qualquer contrato e eu não estou a filtrar nada :/

**Comment by moodyblue** [comment]
Eu tinha criado um userid para fazer estes testes, e com esse userid, mesmo tendo permissão administrativa, não consigo usar o teu script. Tentei de novo mas agora com o userid principal e funcionou

**Comment by moodyblue** [comment]
Pronto, já descobri qual era o problema. Eu criei um utilizador na app, mas na app não disse que esse utilizador tinha acesso ao alarme. Depois de dizer que tem acesso ao alarme este script já funciona com esse novo userid. Vou mudar o título da issue.
